version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hyperativa_bd
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyperativa
      MYSQL_USER: victor
      MYSQL_PASSWORD: victor
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-setup.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - hyper_network

  api:
    container_name: challenge
    build: .
    ports:
        - "8080:8080"
    environment:
       - DB_URL_STRING=jdbc:mysql://mysql:3306/hyperativa
    restart: always
    depends_on: 
       - mysql
    networks:
      - hyper_network

networks:
  hyper_network:
    driver: bridge
